// <auto-generated />
using System;
using AllAddOnsAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AllAddOnsAPI.Migrations
{
    [DbContext(typeof(addOnContext))]
    [Migration("20181123100541_secondCreate")]
    partial class secondCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AllAddOnsAPI.Models.AddOns", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddOnName");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<long>("GroupId");

                    b.Property<string>("IsPromoRecurring");

                    b.Property<long>("Price");

                    b.Property<string>("PromoDescription");

                    b.Property<string>("RecurringPromoId");

                    b.Property<string>("Spiel");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("AddOns");
                });

            modelBuilder.Entity("AllAddOnsAPI.Models.Promos", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<long>("GroupId");

                    b.Property<string>("IsPromoRecurring");

                    b.Property<long>("Price");

                    b.Property<long>("PromID");

                    b.Property<string>("PromoDescription");

                    b.Property<string>("Promoname");

                    b.Property<string>("RecurringPromoId");

                    b.Property<string>("Spiel");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Promos");
                });
#pragma warning restore 612, 618
        }
    }
}
